src/AppBundle/Entity/Faq.php
<?php
namespace AppBundle\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Doctrine\Repository\FaqRepository")
 * @ORM\Table(name="`faq`")
 */
class Faq
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Assert\NotBlank(message="Укажите вопрос")
     * @ORM\Column(type="text")
     */
    protected $question;

    /**
     * @Assert\NotBlank(message="Укажите ответ")
     * @ORM\Column(type="text")
     */
    protected $answer;

    /**
     * @Assert\NotBlank(message="Укажите порядок сортировки")
     * @ORM\Column(type="smallint")
     */
    protected $position = 0;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set question
     *
     * @param string $question
     *
     * @return Faq
     */
    public function setQuestion($question)
    {
        $this->question = $question;

        return $this;
    }

    /**
     * Get question
     *
     * @return string
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * Get short question text
     *
     * @return string
     */
    public function getShortQuestion()
    {
        if (mb_strlen($this->question) > 15) {
            return mb_substr($this->question, 0, 15).'...';
        } else {
            return $this->question;
        }
    }

    /**
     * Set answer
     *
     * @param string $answer
     *
     * @return Faq
     */
    public function setAnswer($answer)
    {
        $this->answer = $answer;

        return $this;
    }

    /**
     * Get answer
     *
     * @return string
     */
    public function getAnswer()
    {
        return $this->answer;
    }

    /**
     * Set position
     *
     * @param integer $position
     *
     * @return Faq
     */
    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return integer
     */
    public function getPosition()
    {
        return $this->position;
    }
}

src/AppBundle/Controller/FaqAdminController.php
<?php

namespace AppBundle\Controller;


use AppBundle\Entity\Faq;
use AppBundle\Form\Type\AdminFaqType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class FaqAdminController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        /** @var \Doctrine\ORM\EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $faqs = $em->getRepository('AppBundle:Faq')
            ->findAll();

        return $this->render('@App/FaqAdmin/index.html.twig', array(
            'faqs' => $faqs,
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function newAction(Request $request)
    {
        /** @var \Doctrine\ORM\EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $faq = new Faq();
        $form = $this->createForm(AdminFaqType::class, $faq, array('new' => true));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($faq);
            $em->flush();
            $this->addFlash('success', 'Вопрос успешно добавлен');
            return $this->redirect($this->generateUrl('admin_faq'));
        }

        return $this->render('@App/FaqAdmin/new.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @param $id
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction($id, Request $request)
    {
        /** @var \Doctrine\ORM\EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $faq = $em->getRepository('AppBundle:Faq')->find($id);
        if (!$faq) {
            throw $this->createNotFoundException('Запись не найдена');
        }
        $form = $this->createForm(AdminFaqType::class, $faq, array('new' => false));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($faq);
            $em->flush();
            $this->addFlash('success', 'Вопрос успешно отредактирован');
            return $this->redirect($this->generateUrl('admin_faq'));
        }

        return $this->render('@App/FaqAdmin/edit.html.twig', array(
            'faq' => $faq,
            'form' => $form->createView(),
        ));
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction($id)
    {
        /** @var \Doctrine\ORM\EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $faq = $em->getRepository('AppBundle:Faq')->find($id);
        if ($faq instanceof Faq) {
            $em->remove($faq);
            $em->flush();
            $this->addFlash('success', 'Вопрос успешно удален');
        } else {
            $this->addFlash('success', 'Не удалось удалить вопрос');
        }

        return $this->redirect($this->generateUrl('admin_faq'));
    }
}

src/AppBundle/Resources/views/FaqAdmin/_form.html.twig
{{ form_start(form, {'attr': {'class': ''}}) }}

{{ form_label(form.question) }}
<br><br>
<div class="field">
    <div class="input__box">
        {{ form_widget(form.question, {'attr': {'class': 'input__text'}}) }}
    </div>
</div><br>
{{ form_label(form.answer) }}
<br><br>
<div class="field">
    <div class="input__box">
        {{ form_widget(form.answer, {'attr': {'class': 'input__text'}}) }}
    </div>
</div><br>
{{ form_label(form.position) }}
<br><br>
<div class="field">
    <div class="input__box">
        {{ form_widget(form.position, {'attr': {'class': 'input__text'}}) }}
    </div>
</div><br>
{{ form_widget(form.submit, {'attr': {'class': 'btn btn--green', 'style': 'margin-bottom: 20px'}}) }}

{{ form_end(form) }}

src/AppBundle/Resources/views/FaqAdmin/edit.html.twig
{% extends '@App/layout/admin.html.twig' %}

{% block title %}{% endblock %}

{% block main_body %}
    <h1 class="offers__h1">Редактирование вопроса "{{ faq.shortQuestion }}"</h1>
    {{ include('@App/FaqAdmin/_form.html.twig') }}
{% endblock %}

src/AppBundle/Resources/views/FaqAdmin/index.html.twig
{% extends '@App/layout/admin.html.twig' %}

{% block title %}{% endblock %}

{% block main_body %}
    <h1 class="offers__h1">Управление часто задаваемыми вопросами</h1>
    <a href="{{ path('admin_faq_new') }}" class="btn btn--green">Добавить вопрос</a>
    {% if faqs|length > 0 %}
        <table class="ui table">
            <thead>
                <tr class="tableheader">
                    <th>ID</th>
                    <th>Вопрос</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for faq in faqs %}
                    <tr class="tablecell">
                        <td>{{ faq.id }}</td>
                        <td>{{ faq.shortQuestion }}</td>
                        <td>
                            <a href="{{ path('admin_faq_edit', {'id': faq.id}) }}" class="btn btn--blue">Редактировать</a>
                            <a href="{{ path('admin_faq_delete', {'id': faq.id}) }}" class="btn btn--red">Удалить</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Нет ни одного вопроса.</p>
    {% endif %}
{% endblock %}

src/AppBundle/Resources/views/FaqAdmin/new.html.twig
{% extends '@App/layout/admin.html.twig' %}

{% block title %}{% endblock %}

{% block main_body %}
    <h1 class="offers__h1">Новый вопрос</h1>
    {{ include('@App/FaqAdmin/_form.html.twig') }}
{% endblock %}