src/AppBundle/Entity/GoogleAccount.php
<?php

namespace AppBundle\Entity;


use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="`google_account`")
 */
class GoogleAccount
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $google_id;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="google_accounts")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $user;

    /**
     * @ORM\Column(type="array")
     */
    protected $token;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $channel_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $channel_name;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    protected $channel_images;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $uploads_playlist_id;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    protected $channel_stats;

    public function getShortChannelName()
    {
        if (strlen($this->channel_name) > 15) {
            return substr($this->channel_name, 0, 15).'...';
        } else {
            return $this->channel_name;
        }
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set googleId
     *
     * @param string $googleId
     *
     * @return GoogleAccount
     */
    public function setGoogleId($googleId)
    {
        $this->google_id = $googleId;

        return $this;
    }

    /**
     * Get googleId
     *
     * @return string
     */
    public function getGoogleId()
    {
        return $this->google_id;
    }

    /**
     * Set token
     *
     * @param array $token
     *
     * @return GoogleAccount
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Get token
     *
     * @return array
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Set user
     *
     * @param \AppBundle\Entity\User $user
     *
     * @return GoogleAccount
     */
    public function setUser(\AppBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \AppBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set channelId
     *
     * @param string $channelId
     *
     * @return GoogleAccount
     */
    public function setChannelId($channelId)
    {
        $this->channel_id = $channelId;

        return $this;
    }

    /**
     * Get channelId
     *
     * @return string
     */
    public function getChannelId()
    {
        return $this->channel_id;
    }

    /**
     * Set channelName
     *
     * @param string $channelName
     *
     * @return GoogleAccount
     */
    public function setChannelName($channelName)
    {
        $this->channel_name = $channelName;

        return $this;
    }

    /**
     * Get channelName
     *
     * @return string
     */
    public function getChannelName()
    {
        return $this->channel_name;
    }

    /**
     * Set channelImages
     *
     * @param array $channelImages
     *
     * @return GoogleAccount
     */
    public function setChannelImages($channelImages)
    {
        $this->channel_images = $channelImages;

        return $this;
    }

    /**
     * Get channelImages
     *
     * @return array
     */
    public function getChannelImages()
    {
        return $this->channel_images;
    }

    /**
     * Set uploadsPlaylistId
     *
     * @param string $uploadsPlaylistId
     *
     * @return GoogleAccount
     */
    public function setUploadsPlaylistId($uploadsPlaylistId)
    {
        $this->uploads_playlist_id = $uploadsPlaylistId;

        return $this;
    }

    /**
     * Get uploadsPlaylistId
     *
     * @return string
     */
    public function getUploadsPlaylistId()
    {
        return $this->uploads_playlist_id;
    }

    /**
     * Set channelStats
     *
     * @param array $channelStats
     *
     * @return GoogleAccount
     */
    public function setChannelStats($channelStats)
    {
        $this->channel_stats = $channelStats;

        return $this;
    }

    /**
     * Get channelStats
     *
     * @return array
     */
    public function getChannelStats()
    {
        return $this->channel_stats;
    }
}

src/AppBundle/Controller/PanelController.php
<?php

namespace AppBundle\Controller;


use AppBundle\Entity\GoogleAccount;
use AppBundle\Entity\Tip;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class PanelController extends Controller
{
    public function ofertaAction()
    {
        return $this->render('@App/Panel/oferta.html.twig');
    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function accountSwitcherAction()
    {
        $current_google_account_id = $this->get('session')->get('current_google_account');
        $google_accounts = $this->getUser()->getGoogleAccounts();
        $current = null;
        foreach ($google_accounts as $google_account) {
            if ($google_account->getId() == $current_google_account_id) {
                $current = $google_account;
            }
        }

        return $this->render('@App/Panel/_account_switcher.html.twig', array(
            'current' => $current,
            'google_accounts' => $google_accounts,
        ));
    }

    /**
     * @return Response
     */
    public function tipsAction()
    {
        /** @var \Doctrine\ORM\EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        if ($this->getUser()->getSettingShowTips()) {
            try
            {
                $tips = $em->getRepository('AppBundle:Tip')
                    ->findAll();
                return $this->render('@App/Panel/_tips.html.twig', array(
                    'tips' => $tips,
                ));
            } catch (\Exception $e) { }
        }
        
        return new Response();
    }

    /**
     * @param Request $request
     * @param $account_id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function switchAccountAction(Request $request, $account_id)
    {
        $this->get('session')->set('current_google_account', $account_id);
        if (!empty($request->get('back'))) {
            return $this->redirect($request->get('back'));
        } else if (!empty($request->headers->get('referer'))) {
            return $this->redirect($request->headers->get('referer'));
        } else {
            return $this->redirect($this->generateUrl('like_index'));
        }
    }

    /**
     * @param $account_id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function refreshAccountAction($account_id)
    {
        /** @var \Doctrine\ORM\EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $account = $em->getRepository('AppBundle:GoogleAccount')
            ->find($account_id);
        if ($account instanceof GoogleAccount && $account->getUser()->getId() == $this->getUser()->getId()) {
            if ($this->get('google')->updateYoutubeChannel($account)) {
                $this->addFlash('success', 'Аккаунт успешно обновлен.');
                return $this->redirect($this->generateUrl('user_profile'));
            }
        }

        $this->addFlash('error', 'Не удалось обновить аккаунт. Попробуйте выполнить привязку повторно.');
        return $this->redirect($this->generateUrl('user_profile'));
    }
}

src/AppBundle/Resources/views/Panel/_account_switcher.html.twig
{% if google_accounts|length > 1 %}
    {% spaceless %}
    <div id="" class="account-dropdown text ui large image dropdown">
        <img src="{{ current.channelImages['default'] }}">
        <p style="font-size: 16px">{{ current.shortChannelName }}</p>
        <i class="dropdown icon"></i>
        <div class="menu">
            {% for google_account in google_accounts %}
                <div class="item" data-url="{{ path('panel_switch_account', {'account_id': google_account.id}) }}">
                    {#<img src="{{ google_account.channelImages['default'] }}">#}
                    <p style="font-size: 16px">{{ google_account.channelName }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
    {% endspaceless %}
    <script>
        $('.account-dropdown').dropdown({
            onChange: function (value, text, $choice) {
                window.location = $choice.data('url');
            }
        });
    </script>
{% elseif google_accounts|length == 1 %}
    <div id="" class="account-dropdown text ui large image">
        <img src="{{ current.channelImages['default'] }}">
        <p style="font-size: 16px">{{ current.shortChannelName }}</p>
    </div>
{% endif %}

src/AppBundle/Resources/views/Panel/_tips.html.twig
<div class="sidebar__box">
    <div class="advises">
        {% if tips|length > 1 %}
            <div class="switch">
                <a href="#" class="switchleft switch__item"><img src="{{ asset('bundles/app/images/to-left.svg') }}" alt=""></a>
                <a href="#" class="switchright switch__item"><img src="{{ asset('bundles/app/images/to-right.svg') }}" alt=""></a>
            </div>
            <script src="{{ asset('bundles/app/js/simpleslider.min.js') }}"></script>
            <script>
                $(function () {
                    $('#slider').css('height', Math.max.apply(null, $(".advises__item").map(function () {
                        return $(this).height();
                    }).get()));
                    var imgSlider = simpleslider.getSlider({
                        delay: 12,
                        prop: 'opacity',
                        unit: '',
                        init: 0,
                        show: 1,
                        end: 0
                    });
                    $('.switchleft').on('click', function (e) {
                        imgSlider.prev();
                        e.preventDefault();
                    });
                    $('.switchright').on('click', function (e) {
                        imgSlider.next();
                        e.preventDefault();
                    });
                })
            </script>
        {% endif %}
        <p class="box__heading">Советы</p>
        <div id="slider" data-simple-slider>
            {% for tip in tips %}
                <div class="advises__item">
                    {% if tip.header is not null %}
                        <p class="item__heading">{{ tip.header }}</p>
                    {% endif %}
                    <p class="item__body">{{ tip.text }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

src/AppBundle/Resources/views/Panel/index.html.twig
{% extends '@App/layout/panel.html.twig' %}

{% block main_body %}
    <h1 class="offers__h1">Панель управления</h1>
    <div class="ui segments">
        <div class="ui segment">
            <h3 class="ui center aligned header">
                <i class="money icon"></i>
                <div class="content">Финансы</div>
            </h3>
        </div>
        <div class="ui segment">
            <p><b>Баланс</b>: {{ app.user.balance.amount }} ₽</p>
            <h4 class="offers__subheader">Последние транзакции:</h4>
            {% if transactions|length %}
                <table class="ui table">
                    {% for transaction in transactions %}
                        <tr class="tablecell">
                            <td>{{ transaction.amount }}</td>
                            <td>{{ transaction.createdAt|date('d.m.Y H:i:s') }}</td>
                            <td>{{ transaction.comment }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p class="label">Транзакций пока нет.</p>
            {% endif %}
        </div>
    </div>
    <div class="ui segments">
        <div class="ui segment">
            <h3 class="ui center aligned header">
                <i class="arrow circle outline up icon"></i>
                <div class="content">Исходищие заявки</div>
            </h3>
        </div>
        <div class="ui segment">
            <h4 class="offers__subheader">Последние заявки:</h4>
            {% if buy_orders|length %}
                <table class="ui table">
                    {% for order in buy_orders %}
                        <tr class="tableheader">
                            <td>{{ order.video }}</td>
                            <td>{{ order.createdAt|date('d.m.Y H:i:s') }}</td>
                            {% if order.status == constant('AppBundle\\Entity\\Order::STATUS_REJECTED') %}
                                <td>Отклонено исполнителем</td>
                            {% elseif order.status == constant('AppBundle\\Entity\\Order::STATUS_EXPIRED') %}
                                <td>Срок предложения истек</td>
                            {% elseif order.status == constant('AppBundle\\Entity\\Order::STATUS_DONE') %}
                                <td>Выполнено</td>
                            {% elseif order.status == constant('AppBundle\\Entity\\Order::STATUS_WAITING') %}
                                <td>Ожидает выполнения</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>Нет исходящих заявок.</p>
            {% endif %}
        </div>
    </div>
    <div class="ui segments">
        <div class="ui segment">
            <h3 class="ui center aligned header">
                <i class="arrow circle outline down icon"></i>
                <div class="content">Входящие заявки</div>
            </h3>
        </div>
        <div class="ui segment">
            <h4 class="offers__subheader">Последние заявки:</h4>
            {% if sell_orders|length %}
                <table class="ui table">
                    {% for order in sell_orders %}
                        <tr class="tableheader">
                            <td>{{ order.video }}</td>
                            <td>{{ order.createdAt|date('d.m.Y H:i:s') }}</td>
                            {% if order.status == constant('AppBundle\\Entity\\Order::STATUS_REJECTED') %}
                                <td>Отклонено исполнителем</td>
                            {% elseif order.status == constant('AppBundle\\Entity\\Order::STATUS_EXPIRED') %}
                                <td>Срок предложения истек</td>
                            {% elseif order.status == constant('AppBundle\\Entity\\Order::STATUS_DONE') %}
                                <td>Выполнено</td>
                            {% elseif order.status == constant('AppBundle\\Entity\\Order::STATUS_WAITING') %}
                                <td>Ожидает выполнения</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p class="label">Нет входящих заявок.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Panel/oferta.html.twig
{% extends '@App/layout/panel.html.twig' %}

{% block main_body %}
<section class="sheet">
    <h1 class="sheet_heading">Публичная оферта по оказанию услуг</h1>
    <pre class="sheet_pre">В настоящей публичной Оферте нижеприведенные термины используются в следующем значении:</pre>
    <h1 class="sheet_heading">1. Термины и определения</h1>
    <pre class="sheet_pre">
1.1 «Заказчик» - любое физическое лицо, которое оформляя отношения с другим физическим лицом (Исполнителем) на предоставление «Услуг» по средством сервиса AdvertPP, принимает (акцептует) настоящее публичное предложение (Оферту).
1.2 «Исполнитель» - любое физическое лицо, которое оформляя отношения с другим физическим лицом (Заказчиком) на предоставление «Услуг» по средствам сервиса AdvertPP, принимает (акцептует) настоящее публичное предложение (Оферту).
1.3 «Услуги» -  действия Исполнителя (физического лица), осуществляемые им от своего имени, но за счет Заказчика, направленные на организацию взаимовыгодного договора по осуществлению ими тех или иных действий в отношении Предмета услуги в рамках площадки YouTube.com
1.4  «YouTube» — интерактивный интернет ресурс (сайт) по оказанию безвозмездных услуг по размещению видео контента в соответствии с законами региона, в котором он (интернет ресурс) зарегистрирован.
1.5 «Лайк» — действие, направленное на оказание положительного отношения и проявления одобрения к материалу Заказчика со стороны Исполнителя, размещенного на интернет ресурсе (сайте) YouTube.com по средствам клика по функциональной кнопке «Мне понравилось».
1.6 «Акцепт оферты» – полное и безоговорочное принятие оферты Заказчиком и Исполнителем путем оформления отношений между собой на сервисе AdvertPP.ru
1.7 «Интернет-сайт» - Интернет-сайт сервиса, размещенный  под доменным именем: www.AdvertPP.ru
1.8 «Договор» - Договор оказания услуг.
1.9 «Предмет услуги» - лайк, призванный оказать свое положительно отношение Исполнителя к видео материалу Заказчика, размещенного на интернет ресурсе (сайте) YouTube.com.
1.10 «Заказ» - оформляемая на Интернет-сайте AdvertPP.ru заявка Заказчика на получение Услуг от Исполнителя, которая содержит согласованную обеими Сторонами информацию о стоимости Предмета услуги, а также о времени его предоставления. Перечень информации, подлежащей согласованию Сторонами при оформлении Заказа, определяется разделом 2 настоящей Оферты. Заказчик, оформляя Заказ на оказание Услуг, информация о которых размещена на Интернет-сайте, принимает (акцептует) настоящее публичное предложение (Оферту) Интернет-сайта AdvertPP.ru о устном заключении Договора с Исполнителем. Предложение о заключении Договора действует в отношении любых Предметов услуги в течение всего периода времени, пока информация о соответствующих Услугах размещена на Интернет-сайте.
С момента подтверждения Заказа на оказание Услуг, оформленного в соответствии с размещенными на Интернет-сайте правилами, между Сторонами, заключен Договор о нижеследующем:
    </pre>
    <h1 class="sheet_heading">2. Предмет Договора</h1>
    <pre class="sheet_pre">
2.1 Заказчик обязуется заключить Договор с Исполнителем в соответствии с прейскурантом Исполнителя на оказание им Услуг и организовать предоставление Услуг Заказчику, а Заказчик обязуется оплатить Услуги Исполнителя на условиях настоящего Договора по средствам Интернет сайта AdvertPP.ru.. Количество и наименование Услуг определяются Заказом, оформленным в соответствии правилами, размещенными на Интернет-сайте.
2.2  Вся информация, которая вводится Заказчиком на Интернет-сайте, используется исключительно для осуществления Услуги Исполнителем, и не будет передана третьим лицам.
2.3 Исполнитель Услуг не несет ответственности за содержание и достоверность информации, предоставленной Заказчиком при оформлении Заказа.
2.4 Интернет-сайт AdvertPP.ru не несет ответственности за информацию размещенную на интернет ресурсе YouTube.com заказчиком, Услугу продвижения которой он (Заказчик) заказывает у Исполнителя.
2.5 Интернет-сайт AdvertPP.ru не несет ответственности за информацию размещенную на интернет ресурсе YouTube.com Исполнителем при регистрации и автоматического парсинга видео контента с интернет ресурса YouTube.com
    </pre>
    <h1 class="sheet_heading">3. Права и обязанности Сторон</h1>
    <pre class="sheet_pre">
3.1 Исполнитель Услуг обязан:
3.1.1 Выполнить взяты на себя обязательства по исполнению Услуги Заказчику согласно принятому к исполнению Заказу.
3.1.2 Отказать в исполнении заявки на оказание Услуг перед Заказчиком, если предоставленный материал Заказчика противоречит законодательству РФ и другим морально-этическим нормам.
3.2 Исполнитель Услуг вправе:
3.2.1 Удержать полную стоимость Заказа в случае указания Заказчиком некорректных данных для исполнения Заказа.
3.3 Заказчик обязан:
3.3.1 Произвести оплату суммы Заказа  в соответствии с условиями оформленного Заказчиком Заказа с Исполнителем. Оплату заказанных Услуг Заказчик вправе производить одним из представленных на Интернет-сайте способов оплаты.
    </pre>
    <h1 class="sheet_heading">4. Дополнительные условия</h1>
    <pre class="sheet_pre">
4.1 Настоящий Договор вступает в силу с момента получения Исполнителем заявки на Услугу Заказа Заказчика и действует до полного исполнения Сторонами обязательств, предусмотренных Договором и вытекающих из него.
4.2 При размещении заявки Заказа Заказчик удостоверяет, что условия настоящего Договора на момент его заключения принимаются им без каких-либо возражений и соответствуют его действительной воле как Заказчика. При размещении Заказа Заказчик уяснил значение используемых в настоящем Договоре терминов, слов и выражений согласно их нормативно-правовому определению и (или) толкованию условий Договора в соответствии с законодательством Российской Федерации.
4.3 Сообщения, направляемые с контактных адресов электронной почты сторон, являются документами, составленными в простой письменной форме и надлежаще подписанными соответствующей стороной (отправителем) аналогом собственноручной подписи. Стороны соглашаются, что такие документы (сообщения) будут иметь юридическую силу без каких-либо дополнительных подтверждений или оформлений (в том числе без их собственноручного подписания), если только иное прямо не указано на сайте агента или не согласовано сторонами.
4.4 Заказчик понимает и подтверждает, что Исполнитель действует по его поручению, что Исполнитель выполняет лишь конкретные условия Заказа заказа Заказчика
4.5 Заказчик и исполнитель понимают и подтверждают, что Интернет-сайт AdvertPP.ru выполняет лишь посреднические функции для Заказчика и Исполнителя и не может нести ответственность за возможные фактические и/или юридические последствия исполнения или не исполнение Договора заключенного между Заказчиком и Исполнителем.
4.6 Заказчик и исполнитель понимают и подтверждают, что Интернет-сайт AdvertPP.ru удерживает комиссию равную комиссии при использовании платежных систем использующихся на Интернет-сайте.
    </pre>
</section>
{% endblock %}